/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.111
 * Generated at: 2025-11-07 05:11:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.recommendType;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/inc/footer.jsp", Long.valueOf(1762417340221L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1762412333374L));
    _jspx_dependants.put("/inc/header.jsp", Long.valueOf(1762492283756L));
    _jspx_dependants.put("jar:file:/C:/Ryuheejae/workspace/Bug-Hunters/project1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project1/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090214156000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>PROJECT1 메뉴추천</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  .fakeimg {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    background: #aaa;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"p-4 bg-primary text-white text-center\">\r\n");
      out.write("    <h1>🍽오늘 뭐 먹지?🍽</h1>\r\n");
      out.write("    <p>사용자 맞춤 추천과 다양한 레시피를 한 눈에!</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/\">Home</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \r\n");
      out.write("            data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" \r\n");
      out.write("            aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <!-- 메뉴 추천 -->\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" \r\n");
      out.write("             data-bs-toggle=\"dropdown\">메뉴 추천</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/recommendAll.recommend\">오늘의 추천</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/recommend/ingredient.jsp\">재료 기반 추천</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/recommend/game.jsp\">미니게임형 추천</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <!-- 음식 검색 -->\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" \r\n");
      out.write("             data-bs-toggle=\"dropdown\">음식 검색</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/search/search.jsp\">키워드/카테고리 검색</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/search/detail.jsp\">음식 상세보기</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <!-- 커뮤니티 -->\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" \r\n");
      out.write("             data-bs-toggle=\"dropdown\">커뮤니티</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.co\">레시피 공유</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.co\">리뷰 게시판</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <!-- 통계 대시보드 -->\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" \r\n");
      out.write("             data-bs-toggle=\"dropdown\">통계 대시보드</a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/stats/myhabit.jsp\">나의 식습관 분석</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/stats/nutrition.jsp\">영양 시각화 그래프</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <!-- 로그인 / 마이페이지 -->\r\n");
      out.write("      <ul class=\"navbar-nav\">\r\n");
      out.write("        ");
 
            String email = (String)session.getAttribute("email");  
            Integer sid = (Integer)session.getAttribute("APPUSERID"); 
            if(email != null){ 
      out.write("\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" \r\n");
      out.write("                   data-bs-toggle=\"dropdown\">");
      out.print(email);
      out.write("</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage.do\">마이페이지</a></li>\r\n");
      out.write("                  <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/잡기능.do\">마이페이지</a></li>\r\n");
      out.write("                  <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/잡기능.do\">마이페이지</a></li>\r\n");
      out.write("                  <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/잡기능.do\">마이페이지</a></li>\r\n");
      out.write("                  <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/잡기능.do\">마이페이지</a></li>        \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/logout.do\">로그아웃</a>\r\n");
      out.write("              </li>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/loginForm.do\">LOGIN</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/view/UserJoin.jsp\">회원가입</a>\r\n");
      out.write("              </li>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container card my-5\">\r\n");
      out.write("  <h3 class=\"card-header\">추천 등록하기</h3>\r\n");
      out.write("  <form action=\"");
      out.print(request.getContextPath());
      out.write("/reg.recommend\" method=\"post\">\r\n");
      out.write("    <div class=\"mb-3 mt-3\">\r\n");
      out.write("      <label for=\"id\" class=\"form-label\">사용자 ID</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"id\" name=\"id\" placeholder=\"사용자 ID를 입력해주세요\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"foodId\" class=\"form-label\">음식 ID</label>\r\n");
      out.write("      <input type=\"number\" class=\"form-control\" id=\"foodId\" name=\"foodId\" placeholder=\"음식 ID를 입력해주세요\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"type\" class=\"form-label\">추천 유형</label>\r\n");
      out.write("      <select class=\"form-select\" id=\"type\" name=\"type\" required>\r\n");
      out.write("        <option value=\"AI\">AI</option>\r\n");
      out.write("        <option value=\"랜덤\">랜덤</option>\r\n");
      out.write("        <option value=\"재료기반\">재료기반</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"feedback\" class=\"form-label\">피드백</label>\r\n");
      out.write("      <textarea class=\"form-control\" id=\"feedback\" name=\"feedback\" placeholder=\"피드백을 입력해주세요\" rows=\"3\"></textarea>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\">등록하기</button>\r\n");
      out.write("    <a href=\"");
      out.print(request.getContextPath());
      out.write("/recommendAll.recommend\" class=\"btn btn-secondary\">목록보기</a>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"mt-5 bg-dark text-white text-center py-4\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <h6 class=\"fw-bold mb-3\">고객지원 / 안내</h6>\r\n");
      out.write("\r\n");
      out.write("    <!-- 텍스트 링크 -->\r\n");
      out.write("    <div class=\"d-flex justify-content-center flex-wrap gap-3\">\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath());
      out.write("/list.co\" class=\"text-white text-decoration-none\">\r\n");
      out.write("        공지사항\r\n");
      out.write("      </a>\r\n");
      out.write("      <span>|</span>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath());
      out.write("/list.co\" class=\"text-white text-decoration-none\">\r\n");
      out.write("        FAQ\r\n");
      out.write("      </a>\r\n");
      out.write("      <span>|</span>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath());
      out.write("/list.co\" class=\"text-white text-decoration-none\">\r\n");
      out.write("        1:1 문의\r\n");
      out.write("      </a>\r\n");
      out.write("      <span>|</span>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath());
      out.write("/list.co\" class=\"text-white text-decoration-none\">\r\n");
      out.write("        이용약관\r\n");
      out.write("      </a>\r\n");
      out.write("      <span>|</span>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath());
      out.write("/list.co\" class=\"text-white text-decoration-none\">\r\n");
      out.write("        개인정보 처리방침\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr class=\"border-secondary my-4\">\r\n");
      out.write("\r\n");
      out.write("    <p class=\"small mb-0\">© 2025 PROJECT1 메뉴 추천 | All Rights Reserved.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<!-- <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
